[package]
name = "bolt-attribute-bolt-system"
description = "Bolt attribute-bolt-system"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["visit-mut"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
bolt-utils = { workspace = true }