[package]
name = "bolt-attribute-bolt-component-deserialize"
description = "Bolt attribute-bolt-component-deserialize"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
bolt-utils = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
sha2 = { workspace = true }
